name: responsive_admin_panel_flutter
description: "Responsive Admin Panel or Dashboard using Flutter"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  fl_chart: ^1.0.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  firebase_core: 3.1.1
  firebase_auth: 5.1.1
  flutter_localization: ^0.2.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  go_router: ^15.2.3
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - lib/
    - lib/core/
    - lib/core/theme/
    - lib/core/utils/
    - lib/core/errors/
    - lib/core/network/
    - lib/core/constants/
    - lib/l10n/
    - lib/routes/
    - lib/features/
    - lib/features/auth/
    - lib/features/auth/data/
    - lib/features/auth/data/models/
    - lib/features/auth/data/data_sources/
    - lib/features/auth/data/repositories/
    - lib/features/auth/domain/
    - lib/features/auth/domain/entities/
    - lib/features/auth/domain/use_cases/
    - lib/features/auth/domain/repositories/
    - lib/features/auth/presentation/
    - lib/features/auth/presentation/cubit/
    - lib/features/auth/presentation/pages/
    - lib/features/auth/presentation/widgets/
    - lib/features/auth/presentation/providers/
    - lib/features/user/
    - lib/features/user/data/
    - lib/features/user/data/models/
    - lib/features/user/data/data_sources/
    - lib/features/user/data/repositories/
    - lib/features/user/domain/
    - lib/features/user/domain/entities/
    - lib/features/user/domain/use_cases/
    - lib/features/user/domain/repositories/
    - lib/features/user/presentation/
    - lib/features/user/presentation/cubit/
    - lib/features/user/presentation/pages/
    - lib/features/user/presentation/widgets/
    - lib/features/user/presentation/providers/
    - lib/features/shared/
    - lib/features/shared/data/
    - lib/features/shared/data/models/
    - lib/features/shared/data/data_sources/
    - lib/features/shared/data/repositories/
    - lib/features/shared/domain/
    - lib/features/shared/domain/entities/
    - lib/features/shared/domain/use_cases/
    - lib/features/shared/domain/repositories/
    - lib/features/shared/presentation/
    - lib/features/shared/presentation/cubit/
    - lib/features/shared/presentation/pages/
    - lib/features/shared/presentation/widgets/
    - lib/features/shared/presentation/providers/
    - lib/features/splash/
    - lib/features/splash/data/
    - lib/features/splash/data/models/
    - lib/features/splash/data/data_sources/
    - lib/features/splash/data/repositories/
    - lib/features/splash/domain/
    - lib/features/splash/domain/entities/
    - lib/features/splash/domain/use_cases/
    - lib/features/splash/domain/repositories/
    - lib/features/splash/presentation/
    - lib/features/splash/presentation/cubit/
    - lib/features/splash/presentation/pages/
    - lib/features/splash/presentation/widgets/
    - lib/features/splash/presentation/providers/
    - lib/features/dashboard/
    - lib/features/dashboard/data/
    - lib/features/dashboard/data/models/
    - lib/features/dashboard/data/data_sources/
    - lib/features/dashboard/data/repositories/
    - lib/features/dashboard/domain/
    - lib/features/dashboard/domain/entities/
    - lib/features/dashboard/domain/use_cases/
    - lib/features/dashboard/domain/repositories/
    - lib/features/dashboard/presentation/
    - lib/features/dashboard/presentation/cubit/
    - lib/features/dashboard/presentation/pages/
    - lib/features/dashboard/presentation/widgets/
    - lib/features/dashboard/presentation/providers/
    - lib/features/generated/
    - lib/features/generated/data/
    - lib/features/generated/data/models/
    - lib/features/generated/data/data_sources/
    - lib/features/generated/data/repositories/
    - lib/features/generated/domain/
    - lib/features/generated/domain/entities/
    - lib/features/generated/domain/use_cases/
    - lib/features/generated/domain/repositories/
    - lib/features/generated/presentation/
    - lib/features/generated/presentation/cubit/
    - lib/features/generated/presentation/pages/
    - lib/features/generated/presentation/widgets/
    - lib/features/generated/presentation/providers/
    - lib/generated/
    - lib/generated/intl/
flutter_intl:
  enabled: true
