name: Flutter CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    strategy:
      matrix:
        target: [apk, web, ios]
    runs-on: ${{ matrix.target == 'ios' && 'macos-latest' || 'ubuntu-latest' }}

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
      - name: Cache pub dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Run tests
        run: flutter test --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage/lcov.info
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Build APK
        if: matrix.target == 'apk'
        run: flutter build apk --release
      - name: Upload APK Artifact
        if: matrix.target == 'apk'
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
      - name: Build Web
        if: matrix.target == 'web'
        run: flutter build web --release
      - name: Upload Web Artifact
        if: matrix.target == 'web'
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web
      - name: Build iOS
        if: matrix.target == 'ios'
        run: flutter build ios --release --no-codesign
      - name: Upload iOS Artifact
        if: matrix.target == 'ios'
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/iphoneos
